---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include overrides specific to RHEL 7.
  include_vars: RedHat-7.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"

- name: Include overrides specific to Fedora.
  include_vars: Fedora.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution == "Fedora"

- include_tasks: server.yml
  when:
    - "'nfsservers' in groups"
    - "ansible_fqdn in groups['nfsservers']"

- include_tasks: client.yml
  when:
    - "'nfsclients' in groups"
    - "ansible_fqdn in groups['nfsclients']"
