---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: pd-nfs-server-stretch
    image: debian:stretch
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs: ['/tmp', '/run', '/run/lock']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - base
  - name: pd-nfs-server-buster
    image: debian:buster
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs: ['/tmp', '/run', '/run/lock']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - base
  - name: pd-nfs-client-stretch
    image: debian:stretch
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs: ['/tmp', '/run', '/run/lock']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - base
  - name: pd-nfs-client-buster
    image: debian:buster
    dockerfile: ../resources/Dockerfile.j2
    command: /sbin/init
    tmpfs: ['/tmp', '/run', '/run/lock']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - base
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
  inventory:
    links:
      group_vars: inventory/group_vars/
      hosts: inventory/hosts
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
